FROM nginx:alpine

RUN apk add --no-cache yq-go

COPY web/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh && \
    mkdir -p /usr/share/nginx/html/config

COPY web/index.html /usr/share/nginx/html/index.html
COPY web/settings.schema.json /usr/share/nginx/html/settings.schema.json
COPY web/dam-pav.logo.svg /usr/share/nginx/html/dam-pav.logo.svg
COPY config/settings.yml.example /usr/share/nginx/html/config/settings.yml.example

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
