FROM nginx:alpine

COPY web/nginx.conf /etc/nginx/conf.d/default.conf

COPY web/index.html /usr/share/nginx/html/index.html
COPY web/settings.schema.json /usr/share/nginx/html/settings.schema.json

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
